---
- hosts: all
  become: yes
  tasks:
   - name: create Docker config directory
     file: path=/etc/docker state=directory

   - name: changing Docker to systemd driver
     copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
        "exec-opts": ["native.cgroupdriver=systemd"]
        }

   - name: install Docker
     apt:
       name: docker.io
       state: present
       update_cache: true

   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present

   - name: Create directory for apt-key
     file:
      path: /etc/apt/keyrings
      state: directory
      mode: "0644"    

   - name: Add an Apt signing key, uses whichever key is at the URL
     ansible.builtin.apt_key:
      url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
      state: present

   - name: add Kubernetes' APT repository
     apt_repository:
      repo: deb https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
      state: present
      filename: kubernetes
      update_cache: true
      mode: 0644

   - name: install kubelet
     apt:
       name: kubelet
       state: present
       update_cache: true

   - name: install kubeadm
     apt:
       name: kubeadm
       state: present

- hosts: control_plane
  become: yes
  tasks:
   - name: install kubectl
     apt:
       name: kubectl
       state: present
       force: yes