---
# handlers file for post-install

- name: restart_rhel_ntp
  service:
    name: ntpd
    state: restarted
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: restart_debian_ntp
  service:
    name: ntp
    state: restarted
    enabled: yes
  when: ansible_os_family == "Debian"